### ISSUE TITLE
ValueError: Number of features of the model must match the input. Model n_features is 211 and input n_features is 275 

### ISSUE THREAD

**Issue by kvr2007** [THGLab/CSpred#13]
Hello!

I downloaded the latest version of the software and the models, and I try to run `CSpred.py test.pdb` I get the following error:

```
Calculating UCBShift-Y predictions ...
Multiple chains exist in this pdb file! Skipping...
No sequence in database generates possible alignments
Generating features ...
Calculating UCBShift-X predictions for C ...
/.../cspred-nmr/lib/python3.8/site-packages/scipy/__init__.py:143: UserWarning: A NumPy version >=1.19.5 and <1.27.0 is required for this version of SciPy (detected version 1.19.0)
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
Traceback (most recent call last):
  File "CSpred.py", line 222, in <module>
    preds = calc_sing_pdb(args.input, args.pH, TP=not args.shiftx_only, ML=not args.shifty_only, test=args.test)
  File "CSpred.py", line 162, in calc_sing_pdb
    r0_pred = r0.predict(atom_feats.values)
  File "/.../cspred-nmr/lib/python3.8/site-packages/sklearn/ensemble/_forest.py", line 766, in predict
    X = self._validate_X_predict(X)
  File "/.../cspred-nmr/lib/python3.8/site-packages/sklearn/ensemble/_forest.py", line 412, in _validate_X_predict
    return self.estimators_[0]._validate_X_predict(X, check_input=True)
  File "/.../cspred-nmr/lib/python3.8/site-packages/sklearn/tree/_classes.py", line 388, in _validate_X_predict
    raise ValueError("Number of features of the model must "
ValueError: Number of features of the model must match the input. Model n_features is 211 and input n_features is 275 
```

Looks like the number of features in the model is calculated differently, what could be the cause here?

**Comment by ptaszeg6** [comment]
Hi! Please try using the updated models available at: https://zenodo.org/records/15375968
Let me know if you run into any other problems with this.

**Comment by kvr2007** [comment]
Yes, it did the trick, thank you :) What is the difference between the new model and the one presented in the publication?
